name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Cd eui-react
      run: cd eui-react
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Build and deploy
      run: |
        yarn build
        git config --global user.name "hopnk"
        git config --global user.email "hopxc1997@gmail.com"
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r build/* .
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
